template:
  name: Horizon
  slug: horizon
  version: 1.0.0
  technology: nextjs-app-router
  description: Next.js 14 static-export site using Tailwind CSS, shadcn/ui, and template-driven
    design tokens.
scaffolding:
  layout_file: app/layout.tsx
  providers_file: app/providers.tsx
  global_styles: app/globals.css
  route_base_dir: app
  component_catalog_dir: src/components
  ui_library_dir: src/components/ui
  hooks_dir: src/hooks
  assets_dir: public/assets
  examples_dir: page-examples
page_generation:
  scaffold_method: create_route_directory
  client_component_required: true
  navigation_component: src/components/Navigation.tsx
  footer_component: src/components/Footer.tsx
  section_components:
  - Hero
  - Services
  - WhyChooseUs
  - Testimonials
  - FinalCTA
  - About
  metadata_strategy:
    global: app/layout.tsx
    per_page: optional export of `const metadata` within page files
  duplicate_examples: []
  assets_path_hint: /assets/...
style_guide:
  enabled: true
  route: app/style-guide/page.tsx
  template_path: app/style-guide/template.tsx
  voice_notes_section: '### Voice & Tone'
  requires_approval: false
  notes: Generate three fully rendered variants under /style-guide/<slug> before skeletons.
    Each variant must include palette, typography, voice, and hero samples.
rotation_rules:
  hero:
    variants: []
    notes: No enforced rotation yet; update when additional hero components ship.
  closing_cta:
    variants: []
    notes: Reuse FinalCTA as needed until multiple CTA layouts exist.
imagery:
  workflow_ref: ../../images/images-overview.md
  run_after: copy_approved
testing:
  commands:
  - npm run lint
  - npm run build
notes:
- Always mark page-level files and new interactive sections with 'use client'.
- Reference Tailwind tokens in app/globals.css; introduce new tokens via tailwind.config.ts
  before use.
- Register project-specific heading/body fonts via `next/font` (or equivalent) and
  map them to the `--font-serif` and `--font-body` variables before shipping.
- Import section components from src/components; avoid duplicating markup manually.
- Keep the /style-guide route in sync with any token or helper-class change so QA
  catches regressions before page updates.
theming:
  color_tokens_file: app/globals.css
  tailwind_extend_file: tailwind.config.ts
  font_strategy: next/font in app/layout.tsx
  icon_library:
    type: npm_package
    package: lucide-react
    usage: Import icons from 'lucide-react' and keep selections consistent with the
      brand direction logged in automation state.
