services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    command: sh -c "pnpm install --frozen-lockfile && pnpm dev --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    working_dir: /app/client
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - frontend-node-modules:/app/client/node_modules
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: ./backend
    command: sh -c "uv sync --frozen --no-dev && uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      - backend-uv-cache:/root/.cache/uv

  form-relay:
    build:
      context: ./services/form-relay
    command: sh -c "uv sync --frozen --no-dev && uv run uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload"
    ports:
      - "8080:8080"
    working_dir: /app
    env_file:
      - ./services/form-relay/.env
    volumes:
      - ./services/form-relay:/app
      - form-relay-uv-cache:/root/.cache/uv
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  frontend-node-modules:
  backend-uv-cache:
  form-relay-uv-cache:
