/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    /**
     * Health check
     * @description Return operational metadata used by availability probes.
     */
    get: operations["health_health_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * HealthCheckResponse
     * @description Standard payload returned by the health check endpoint.
     */
    HealthCheckResponse: {
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "degraded" | "error";
      service: components["schemas"]["ServiceMetadata"];
      /**
       * Message
       * @default Service is healthy
       */
      message?: string;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp?: string;
    };
    /**
     * ServiceMetadata
     * @description Metadata describing the running backend service.
     */
    ServiceMetadata: {
      /** Name */
      name: string;
      /** Version */
      version: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Health check
   * @description Return operational metadata used by availability probes.
   */
  health_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthCheckResponse"];
        };
      };
    };
  };
}
