name: website_build
summary: Hybrid workflow for building static site exports with coordinator-led multi-agent stages.
inputs:
  site_slug: string
  template_slug: string
plugins:
  manifest: templates/{{ template_slug }}/agents/plugins.yaml
  defaults:
    visual_system:
      enabled: false
    asset_pipeline:
      enabled: false
    release:
      tools: []
hooks:
  manifest: templates/{{ template_slug }}/agents/hooks.yaml
  optional: true
stages:
  - id: repo_prep
    label: repo-prep
    role: coordinator
    prompt: ../coordinator.md
    summary: Ensure workspace, template assets, and guardrails are ready before authorizing build work.
    outputs: [workspace_ready]
    hooks:
      extend: repo_prep

  - id: intake
    label: intake
    role: brief_synthesizer
    prompt: roles/brief_synthesizer.md
    requires: [workspace_ready]
    outputs: [client_overview_path, page_list]
    gates: []

  - id: plan
    label: planning
    role: coordinator
    prompt: ../coordinator.md
    requires: [client_overview_path, page_list]
    uses:
      - templates/{{ template_slug }}/config.yaml
      - templates/{{ template_slug }}/sections.yaml
    outputs: [section_usage_tracker]
    hooks:
      extend: plan

  - id: visual_system
    label: visual-system
    role: coordinator
    prompt: ../coordinator.md
    requires: [section_usage_tracker]
    condition: plugins.visual_system.enabled
    uses:
      - templates/{{ template_slug }}/tokens.yaml
      - templates/{{ template_slug }}/style-guides/**/*.md
    outputs: [style_token_manifest]
    gates: [coordinator_check]

  - id: skeletons
    label: skeletons
    role: skeleton_builder
    prompt: roles/skeleton_builder.md
    foreach: page in page_list.approved
    requires:
      - section_usage_tracker
    optional_requires:
      - style_token_manifest
    gates: [coordinator_check]

  - id: copy
    label: copy
    role: copy_drafter
    prompt: roles/copy_drafter.md
    foreach: page in page_list.approved
    requires:
      - skeletons.page.workspace_path
    gates: [coordinator_check]

  - id: assets
    label: asset-pipeline
    role: assembler
    prompt: roles/assembler.md
    condition: plugins.asset_pipeline.enabled
    tools:
      - pnpm run assets:sync
      - pnpm run assets:upload
    outputs: [asset_pipeline_log]
    gates: [coordinator_check]

  - id: assembly
    label: assembly
    role: assembler
    prompt: roles/assembler.md
    requires:
      - copy
    optional_requires:
      - asset_pipeline_log
    tools:
      - public-sites/scripts/build-static-site.sh {{ site_slug }} --dry-run
    outputs: [assembly_report]
    gates: [human_approval]

  - id: qa
    label: qa
    role: qa_agent
    prompt: roles/qa_agent.md
    requires:
      - assembly_report
    tools:
      - public-sites/checks/base.yaml
    outputs: [qa_report]
    gates: [coordinator_check]

  - id: release
    label: release
    role: release_agent
    prompt: roles/release_agent.md
    requires: [qa_report]
    tools: plugins.release.tools
    outputs: [deployment_log]
    gates: [human_approval]
